export enum ContractStep {
    UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS',
    DOCUMENT_APPROVAL = 'DOCUMENT_APPROVAL',
    PAYMENT_APPROVAL = 'PAYMENT_APPROVAL',
    CLIENT_APPROVAL = 'CLIENT_APPROVAL'
}

